language: cpp

sudo: required

cache: ccache

dist: focal

matrix:
  include:
    - env: VERSION=8 BITS=64
      compiler: gcc
      os: linux


before_install:
  - ./travis.sh before_install

before_script:
  - ./travis.sh before_script

script:
  - ./travis.sh script

after_success:
  - ./travis.sh after_success
