name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo add-apt-repository universe && sudo apt-get update
    - name: getdeps
      run: sudo apt-get -y install git libwxgtk3.0-gtk3-dev libgtk-3-dev debhelper cmake chrpath \
            libsdl2-image-dev libsdl2-ttf-dev \
            dh-autoreconf libasound2-dev libgl1-mesa-dev \
            liblzo2-dev libmpcdec-dev libsamplerate0-dev libsndio-dev \
            libtrio-dev libvorbisidec-dev x11proto-core-dev zlib1g-dev \
            pkg-config lsb-release libao-dev \
            libavformat-dev libbluetooth-dev libcurl4-gnutls-dev \
            libenet-dev libevdev-dev libgtk2.0-dev \
            libopenal-dev libmbedtls-dev libpulse-dev \
            libsfml-dev libsoil-dev libswscale-dev libudev-dev \
            libwxbase3.0-dev libxext-dev libx11-xcb-dev libsdl2-mixer-dev \
            portaudio19-dev qtbase5-private-dev libsamplerate0-dev libfreetype6-dev libglu1-mesa-dev nasm \
            libboost-system-dev libswresample-dev libglew-dev libsnappy-dev libavutil-dev \
            libaio-dev liblzma-dev libpcap0.8-dev libpng-dev libsoundtouch-dev libxml2-dev libx11-dev locales zip build-essential libzstd-dev
            #libsdl2-dev autotools-dev libjack-dev libsndfile1-dev dpkg-dev libavcodec-dev libegl1-mesa-dev 
            #libminiupnpc-dev libreadline-dev libusb-1.0-0-dev libxrandr-dev libboost-filesystem-dev libaio-dev            
            
    - name: aclocal
      run: aclocal
    - name: autoconf
      run: autoconf
    - name: automake
      run: automake --add-missing --foreign
    
    - name: configure
      run: ./configure
    - name: make
      run: make
    
      
      
      
